# Generated by Django 5.1.2 on 2024-10-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='photo',
        ),
    ]
